#
# MongoDB dockers:
#   - mongo engine
#   - mongo UI
#
# Thiebolt.F jun.19     yaml initial release
# Thiebolt.F Oct.18     added --bind_ip_all option
# Thiebolt.F Mars 2017  initial release

version: "3.5"

volumes:
  mydata:
    # external means it ought to get created outside of compose
    external: true
    # TODO: rename volume name and change it below
    name: petitbk

services:

  domoticz:
    image: sdesbure/domoticz
    restart: unless-stopped
    # container_names implies only one instance
    container_name: Domoticz0
    volumes:
      - /etc/localtime:/etc/localtime:ro
     # - /dockyard/volumes/Database/
    network_mode: bridge
    # Port mapping between localhost and the container
    ports:
      - "8080:8080"
    # node red
    #command : 
    command: -wwbind 172.17.0.1 -verbose 1
    #none


  node-red:
    image: nodered/node-red
    restart: unless-stopped
    # container_names implies only one instance
    container_name: NodeRed0
    volumes:
      - /etc/localtime:/etc/localtime:ro
     # - /dockyard/volumes/Database/
    network_mode: bridge
    # Port mapping between localhost and the container
    ports: 
      - "1880:1880" 
    # node red
    #command :
    command: --wbind 172.17.0.1 -verbose 1 
    #none

  mongo:
    image: mongo 
    restart: unless-stopped
    # container_name implies only one instance
    container_name: DataBaseMongo0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mydata:/data/db
    network_mode: bridge
    # Port mapping between the localhost and the container
    ports:
      - "27017:27017"     # mongo engine
    #command:           --bind_ip_all --wiredTigerCacheSizeGB 24   
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    container_name: mongo-express0
    ports:
      - "27016:8081"
    depends_on:
      - mongo
    environment:
     # ME_CONFIG_BASICAUTH_USERNAME: admin
     # ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: 172.17.0.1
      ME_CONFIG_MONGODB_PORT: 27017
    
    

