
# configuration
APP = main
STLINK_ROOT=stlink-1.5.1/build/Release
LOG = stm32f4.log
#GDB = gdb-multiarch
GDB = gdb
GDB_FLAGS=-command ../scripts/gdbinit

# rules
all:
	cd src; $(MAKE) all

clean:
	rm -f $(LOG)
	cd src; $(MAKE) clean

openocd:
	-rm $(LOG)
	openocd -f scripts/openocd.cfg

debug:
	gdb-multiarch src/$(APP).elf

log:
	tail -f $(LOG)


# exercises
ex1:
	cd src; $(MAKE) ex1.elf

ex2:
	cd src; $(MAKE) ex2.elf

ex3:
	cd src; $(MAKE) ex3.elf

ex4:
	cd src; $(MAKE) ex4.elf

ex5:
	cd src; $(MAKE) ex5.elf

ex6:
	cd src, $(MAKE) ex6.elf

ex7:
	cd src; $(MAKE) ex7.elf

ex8:
        cd src; $(MAKE) ex8.elf

ex9:
        cd src; $(MAKE) ex9.elf

ex10:
        cd src; $(MAKE) ex10.elf

ex11:
        cd src; $(MAKE) ex11.elf


debug_ex1: ex1
	cd src; $(GDB) $(GDB_FLAGS) ex1.elf

debug_ex2: ex2
	cd src; $(GDB) $(GDB_FLAGS) ex2.elf

debug_ex3: ex3
	cd src; $(GDB) $(GDB_FLAGS) ex3.elf

debug_ex4: ex4
	cd src; $(GDB) $(GDB_FLAGS) ex4.elf

debug_ex5: ex5
	cd src; $(GDB) $(GDB_FLAGS) ex5.elf

debug_ex6: ex6
        cd src; $(GDB) $(GDB_FLAGS) ex6.elf

debug_ex7: ex7
        cd src; $(GDB) $(GDB_FLAGS) ex7.elf

debug_ex8: ex8
        cd src; $(GDB) $(GDB_FLAGS) ex8.elf

debug_ex9: ex9
        cd src; $(GDB) $(GDB_FLAGS) ex9.elf

debug_ex10: ex10
        cd src; $(GDB) $(GDB_FLAGS) ex10.elf

debug_ex11: ex11
        cd src; $(GDB) $(GDB_FLAGS) ex11.elf


# build distribution
DIST_FILES = \
	COPYING.md \
	.gdbinit \
	include \
	scripts
DIST_SRC = \
	src/Makefile \
	src/startup.c \
	src/tinyprintf.c \
	src/ex?.c
DIST_NAME=labwork1

dist:
	if [ -e $(DIST_NAME) ]; then \
		rm -rf $(DIST_NAME); \
	fi
	mkdir $(DIST_NAME)
	cp -R $(DIST_FILES) $(DIST_NAME)
	mkdir $(DIST_NAME)/src
	cp scripts/Makefile.014 $(DIST_NAME)/Makefile
	for f in $(DIST_SRC); do \
		autofilter.py < $$f > $(DIST_NAME)/$$f; \
	done
	cd $(DIST_NAME); make; make clean
	tar cvfz $(DIST_NAME).tgz $(DIST_NAME)


